name: Publish
on:
  release:
    types:
      - created

concurrency:
  group: env-${{ github.ref }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Setup node and .npmrc
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@simplicity-tech'

      - name: Install packages
        run: yarn

      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
